# Generated by Django 3.2.8 on 2021-10-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.TextField()),
                ('size', models.IntegerField(choices=[('Small', 50), ('Medium', 100), ('Big', 200)])),
                ('temperature', models.FloatField(choices=[('Default', 1.0), ('Creative', 1.2), ('Very Creative', 1.5)])),
            ],
        ),
    ]
